### ISSUE TITLE
cFos Firmware 1.20 is not supported by this plugin

### ISSUE THREAD

**Issue by MrRickwi** [mb-software/homeassistant-powerbrain#56]
I updated my Wallbox to cFos Firmware 1.20, and now the plugin is not able to connect to my Wallbox.

My log shows the following:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Source: custom_components/powerbrain/sensor.py:82
Integration: cFos Powerbrain (documentation, issues)
First occurred: 07:42:46 (84 occurrences)
Last logged: 07:50:04

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 204, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 349, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 146, in async_update_listeners
    update_callback()
  File "/config/custom_components/powerbrain/sensor.py", line 82, in _handle_coordinator_update
    new_value = self.device.attributes[self.attribute]
TypeError: string indices must be integers

**Comment by mb-software** [comment]
Thanks for reporting. In fact cFos has changed the API without notice. I will provide a fix very soon.

**Comment by MrRickwi** [comment]
Works and thanks a lot
